### ISSUE TITLE
Train loop

### ISSUE THREAD

**Issue by mazenmel** [YichengWu/PhaseCam3D#1]
Hi,
Thank you for this very interesting work, I have a question about the training loop in depth_estimation.py, the network is being trained on the same initial batch, I think you should also include the batch extraction lines in the loop. Thanks!

**Comment by YichengWu** [comment]
Hi Mazen, I am glad you are interested in my work! I am not sure if I understand your question correctly. In the `read2batch` function, the data is defined to be shuffled. Every time I read a batch from the dataset, it will be a random batch.

**Comment by mazenmel** [comment]
Thank you for the response, yes but how is read2batch invoked in every training iteration? Is it called within train_op.run() because I didn't fully understand it. Thanks!

**Comment by mazenmel** [comment]
Thank you, I didn't fully understand the training loop, now I do and it makes sense, the train_op() in each iteration will call read2batch to generate new batches.
