### ISSUE TITLE
For detail of phi^{dp}.

### ISSUE THREAD

**Issue by ZERO2ER0** [YichengWu/PhaseCam3D#2]
Hi, I am very interested in your work. I have a problem about $\phi^{DF}$. How to get the analytical expression of $\phi^{DF}$ ? Please help me! Thank you very much!

**Comment by YichengWu** [comment]
Hi, thanks for your interest! The analytical expression can be found in my paper: https://ieeexplore.ieee.org/document/8747330. If you are curious where this formula is coming from, I would recommend you to look at _Introduction to Fourier Optics_, there is one section about _Aberrations and Their Effects on Frequency Response - Example of a Simple
Aberration: A Focusing Error_. I hope this helps.

**Comment by ZERO2ER0** [comment]
> Hi, thanks for your interest! The analytical expression can be found in my paper: https://ieeexplore.ieee.org/document/8747330. If you are curious where this formula is coming from, I would recommend you to look at _Introduction to Fourier Optics_, there is one section about _Aberrations and Their Effects on Frequency Response - Example of a Simple Aberration: A Focusing Error_. I hope this helps.

Thanks for your response! The problem is solved! Thanks again!
