### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by gravitychen** [YichengWu/PhaseCam3D#3]
Dear Author,

Thank you for your great work! Actually, I am new to computational imaging, so I am wondering how to implement differentiable PSF, can you share your supplementary material? because I cannot find it on your project page. 

I learned your code but it is hard for me to fully understand it, sorry! can you also recommend some tutorials about this part? Thank you very much~~ dalao

**Comment by YichengWu** [comment]
Hi, I have uploaded the supp into the [project page](https://yichengwu.github.io/PhaseCam3D/). Please check it out.

**Comment by gravitychen** [comment]
Thank you so so much!
